version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: keycloak
    ports:
      - "18080:8080"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./import:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/demo-realm-export.json


  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
