version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    ports:
      - "18080:8080"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./import:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/demo-realm-export.json
