openapi: 3.0.0
info:
  title: User Authentication API
  version: 1.0.0
  description: An API for user registration, login, and password reset.

servers:
  - url: https://api.example.com/v1

paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                  maxLength: 30
              required:
                - name
                - email
                - password
      responses:
        '200':
          description: User registered successfully
        '400':
          description: Invalid request body
        '409':
          description: User with provided email already exists

  /login:
    post:
      summary: Login to the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                  maxLength: 30
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful
        '400':
          description: Invalid request body
        '401':
          description: Invalid email or password

  /reset-password:
    post:
      summary: Reset user password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
              required:
                - email
      responses:
        '200':
          description: Password reset instructions sent successfully
        '400':
          description: Invalid request body
        '404':
          description: User with provided email not found